com::example::app::DollarRate
ArrayList<DollarRate> com.example.app.DollarRate.dollarRates
String com.example.app.DollarRate.currency
double com.example.app.DollarRate.dollarRate
Date com.example.app.DollarRate.lastUpdated
com.example.app.DollarRate.DollarRate(String currency, double dollarRate)
References com.example.app.DollarRate.addDollarRate, com.example.app.DollarRate.setDollarRate, com.example.app.DollarRate.setLastUpdated.
String com.example.app.DollarRate.getCurrency()
double com.example.app.DollarRate.getDollarRate()
Referenced by com.example.app.Settings.btnChangeRateOnAction, com.example.app.Settings.setRatePromptText, com.example.app.Settings.ViewRateLabel.
void com.example.app.DollarRate.setDollarRate(double dollarRate)
Referenced by com.example.app.DollarRate.DollarRate.
Date com.example.app.DollarRate.getLastUpdated()
Referenced by com.example.app.AddRate.addRateOnAction.
void com.example.app.DollarRate.setLastUpdated()
Referenced by com.example.app.DollarRate.DollarRate.
static void com.example.app.DollarRate.clearDollarRates()
static void com.example.app.DollarRate.loadDollarRates()
References com.example.app.DatabaseConnection.getDollarRates.
Referenced by com.example.app.LoginScreen.main.
static String com.example.app.DollarRate.getCurrencies()
static void com.example.app.DollarRate.addDollarRate(DollarRate dollarRate)
Referenced by com.example.app.DollarRate.DollarRate.
static void com.example.app.DollarRate.removeDollarRate(String currency)
References com.example.app.DatabaseConnection.deleteDollarRate.
Referenced by com.example.app.RemoveRate.DeleteRateOnAction.
static ArrayList< DollarRate > com.example.app.DollarRate.getDollarRates()
static void com.example.app.DollarRate.ChangeDollarRate(String currency, double dollarRate)
References com.example.app.DatabaseConnection.ChangeDollarRate.
Referenced by com.example.app.Settings.btnChangeRateOnAction.
static double com.example.app.DollarRate.getDollarRate(String currency)
static ArrayList< String > com.example.app.DollarRate.getCurrencyList()
Referenced by com.example.app.AddExpense.initialize, com.example.app.RemoveRate.initialize, com.example.app.Settings.initialize.
static Boolean com.example.app.DollarRate.isCurrency(String currency)
Referenced by com.example.app.AddRate.addRateOnAction.
void com.example.app.DollarRate.addDbDollarRate(String currency, double dollarRate, Date lastUpdated)