com::example::app::User
String com.example.app.User.username
String com.example.app.User.password
String com.example.app.User.fonction
ArrayList<User> com.example.app.User.Userlist
com.example.app.User.User()
com.example.app.User.User(String username, String password, String fonction)
String com.example.app.User.getUsername()
String com.example.app.User.getPassword()
String com.example.app.User.getFonction()
void com.example.app.User.setUsername(String username)
void com.example.app.User.setPassword(String password)
void com.example.app.User.setFonction(String fonction)
static ArrayList< User > com.example.app.User.getUserlist()
Referenced by com.example.app.Settings.btnaddUseronAction.
static ArrayList< String > com.example.app.User.getUsernamelist()
Referenced by com.example.app.Settings.btnaddUseronAction, com.example.app.Settings.btnChangePasswordonAction, com.example.app.Settings.btnDeleteUseronAction, com.example.app.Settings.initialize.
static Boolean com.example.app.User.isAvailable(String username)
Referenced by com.example.app.LoginController.LoginButtonAction.
static String com.example.app.User.getPasswordbyuser(String username)
Referenced by com.example.app.Settings.btnChangePasswordonAction, com.example.app.LoginController.LoginButtonAction.
static String com.example.app.User.getFonctionbyuser(String username)
Referenced by com.example.app.Settings.btnChangefonction, com.example.app.Settings.onUserfccbChanged.
static void com.example.app.User.ChangePassword(String username, String password)
References com.example.app.DatabaseConnection.changePassword.
Referenced by com.example.app.Settings.btnChangePasswordonAction.
static void com.example.app.User.ChangeFonction(String username, String fonction)
References com.example.app.DatabaseConnection.changeFonction.
Referenced by com.example.app.Settings.btnChangefonction.
static void com.example.app.User.DeleteByFonction(String fonction)
References com.example.app.DatabaseConnection.deleteUser.
Referenced by com.example.app.Fonction.deleteFonction.
static void com.example.app.User.deleteUser(String username)
References com.example.app.DatabaseConnection.deleteUser.
Referenced by com.example.app.Settings.btnDeleteUseronAction.
static void com.example.app.User.printUserList()
Referenced by com.example.app.Settings.btnaddUseronAction, com.example.app.LoginScreen.main.