com::example::app::Category
String com.example.app.Category.category
ArrayList<Category> com.example.app.Category.categories
com.example.app.Category.Category(String category)
References com.example.app.Category.setCategory.
String com.example.app.Category.getCategory()
void com.example.app.Category.setCategory(String category)
Referenced by com.example.app.Category.Category.
String com.example.app.Category.getName()
static boolean com.example.app.Category.CategoryNotAvailable(String newCategory)
Referenced by com.example.app.MenuItem.setCategory, com.example.app.AddMenuItem.setCategorycb.
static Category com.example.app.Category.getCategory(String category)
Referenced by com.example.app.MenuItem.setCategory.
static ArrayList< String > com.example.app.Category.getCategories()
Referenced by com.example.app.AddMenuItem.initialize, com.example.app.EditMenuItem.initialize.
void com.example.app.Category.AddCategory(String category)