com::example::app::DatabaseConnection
final String com.example.app.DatabaseConnection.uri
final MongoClientURI com.example.app.DatabaseConnection.clientURI
final MongoClient com.example.app.DatabaseConnection.mongoClient
final String com.example.app.DatabaseConnection.ALGORITHM
final String com.example.app.DatabaseConnection.key
MongoDatabase com.example.app.DatabaseConnection.database
static void com.example.app.DatabaseConnection.startConnection()
static void com.example.app.DatabaseConnection.stopConnection()
static ArrayList< DollarRate > com.example.app.DatabaseConnection.getDollarRates()
Referenced by com.example.app.DollarRate.loadDollarRates.
static ArrayList< String > com.example.app.DatabaseConnection.getCategories()
static ArrayList< Expenses > com.example.app.DatabaseConnection.getExpenses()
Referenced by com.example.app.LoginScreen.main.
static ArrayList< String > com.example.app.DatabaseConnection.getFonction()
Referenced by com.example.app.Fonction.loadFonction.
static void com.example.app.DatabaseConnection.LoadUsers()
Referenced by com.example.app.LoginScreen.main.
static void com.example.app.DatabaseConnection.changePassword(String username, String password)
Referenced by com.example.app.User.ChangePassword.
static void com.example.app.DatabaseConnection.changeFonction(String username, String fonction)
Referenced by com.example.app.User.ChangeFonction.
static void com.example.app.DatabaseConnection.deleteUser(String username)
Referenced by com.example.app.User.DeleteByFonction, com.example.app.User.deleteUser.
static void com.example.app.DatabaseConnection.deleteFonction(String fonctionname)
Referenced by com.example.app.Fonction.deleteFonction.
static void com.example.app.DatabaseConnection.addUser(String username, String password, String fonction)
Referenced by com.example.app.Settings.btnaddUseronAction.
static Document com.example.app.DatabaseConnection.getAllUsers()
static void com.example.app.DatabaseConnection.addFonction(String newFonction, Boolean vieworderPanel, Boolean neworderPanel, Boolean expensesPanel, Boolean settingsPanel, Boolean reportsPanel, Boolean menuitemsPanel)
Referenced by com.example.app.Settings.btnAddFonction.
static void com.example.app.DatabaseConnection.addDollarRate(String currency, double dollarRate, Date lastUpdated)
Referenced by com.example.app.AddRate.addRateOnAction.
static void com.example.app.DatabaseConnection.addExpense(String name, String description, int amount, Date date, String currency)
static void com.example.app.DatabaseConnection.deleteExpense(String name)
Referenced by com.example.app.Expenses.removeExpense.
static void com.example.app.DatabaseConnection.loadMenuItems()
Referenced by com.example.app.LoginScreen.main.
static void com.example.app.DatabaseConnection.addMenuItem(MenuItem menuItem)
Referenced by com.example.app.AddMenuItem.btnaddMenuItem.
static void com.example.app.DatabaseConnection.deleteMenuItem(String name)
Referenced by com.example.app.MenuItemPanel.initialize.
static void com.example.app.DatabaseConnection.changeMenuItem(String name, String description, String category, double price, ArrayList< String > ingredients)
Referenced by com.example.app.EditMenuItem.setBtnapply.
static void com.example.app.DatabaseConnection.loadCategories()
Referenced by com.example.app.LoginScreen.main.
static void com.example.app.DatabaseConnection.addCategory(String category)
static void com.example.app.DatabaseConnection.deleteCategory(String category)
void com.example.app.DatabaseConnection.ChangePassword(String username, String NewPassword)
void com.example.app.DatabaseConnection.DeleteUser(String username)
void com.example.app.DatabaseConnection.ChangeFonction(String username, String NewFonction)
void com.example.app.DatabaseConnection.ChangeDollarRate(String currency, double newDollarRate, Date lastUpdated)
Referenced by com.example.app.DollarRate.ChangeDollarRate.
void com.example.app.DatabaseConnection.deleteDollarRate(String currency)
Referenced by com.example.app.DollarRate.removeDollarRate.