com::example::app::Expenses
ArrayList<Expenses> com.example.app.Expenses.allExpenses
int com.example.app.Expenses.totalExpenses
int com.example.app.Expenses.totalAmount
int com.example.app.Expenses.amount
String com.example.app.Expenses.description
String com.example.app.Expenses.name
int com.example.app.Expenses.id
String com.example.app.Expenses.date
String com.example.app.Expenses.currency
com.example.app.Expenses.Expenses()
com.example.app.Expenses.Expenses(String name, String description, int amount, Date date, String currency)
int com.example.app.Expenses.getAmount()
String com.example.app.Expenses.getDescription()
String com.example.app.Expenses.getName()
int com.example.app.Expenses.getId()
String com.example.app.Expenses.getCurrency()
String com.example.app.Expenses.getDate()
void com.example.app.Expenses.setAmount(int amount)
void com.example.app.Expenses.setDescription(String description)
void com.example.app.Expenses.setName(String name)
void com.example.app.Expenses.setId()
void com.example.app.Expenses.setDate(Date date)
void com.example.app.Expenses.setCurrency(String currency)
static int com.example.app.Expenses.getTotalExpenses()
static int com.example.app.Expenses.getTotalAmount()
static ArrayList< Expenses > com.example.app.Expenses.getAllExpenses()
Referenced by com.example.app.Expense.initialize.
static ArrayList< String > com.example.app.Expenses.getAllExpensesNames()
Referenced by com.example.app.RemoveExpense.initialize.
static void com.example.app.Expenses.removeExpense(String name)
References com.example.app.DatabaseConnection.deleteExpense.
Referenced by com.example.app.RemoveExpense.btnRemoveExpenseActionPerformed.
static Boolean com.example.app.Expenses.checkExpense(String name)
static void com.example.app.Expenses.removeAllExpenses()