com::example::app::Fonction
ArrayList<String> com.example.app.Fonction.Fonctionlist
String com.example.app.Fonction.fonctionname
Boolean com.example.app.Fonction.vieworderPanel
Boolean com.example.app.Fonction.neworderPanel
Boolean com.example.app.Fonction.expensesPanel
Boolean com.example.app.Fonction.settingsPanel
Boolean com.example.app.Fonction.reportsPanel
Boolean com.example.app.Fonction.menuitemsPanel
com.example.app.Fonction.Fonction()
com.example.app.Fonction.Fonction(String fonctionname, Boolean vieworderPanel, Boolean neworderPanel, Boolean expensesPanel, Boolean settingsPanel, Boolean reportsPanel, Boolean menuitemsPanel)
Boolean com.example.app.Fonction.isEqual(String fonctionname)
void com.example.app.Fonction.setPanels(Boolean vieworderPanel, Boolean neworderPanel, Boolean expensesPanel, Boolean settingsPanel, Boolean reportsPanel, Boolean menuitemsPanel)
void com.example.app.Fonction.setFonction(String fonctionname)
void com.example.app.Fonction.setFonctionname(String fonctionname)
static void com.example.app.Fonction.loadFonction()
References com.example.app.DatabaseConnection.getFonction.
Referenced by com.example.app.LoginScreen.main.
static ArrayList< String > com.example.app.Fonction.getFonctionlist()
Referenced by com.example.app.Settings.btnAddFonction, com.example.app.Settings.btnChangefonction, com.example.app.Settings.btnDeleteFonction, com.example.app.Settings.initialize.
static int com.example.app.Fonction.getFonctionlistlenght()
static void com.example.app.Fonction.deleteFonction(String fonctionname)
References com.example.app.User.DeleteByFonction, com.example.app.DatabaseConnection.deleteFonction.
Referenced by com.example.app.Settings.btnDeleteFonction.
static void com.example.app.Fonction.clearFonctionlist()