com::example::app::MenuItem
String com.example.app.MenuItem.name
String com.example.app.MenuItem.description
Category com.example.app.MenuItem.category
double com.example.app.MenuItem.price
ArrayList<String> com.example.app.MenuItem.ingredients
ArrayList<MenuItem> com.example.app.MenuItem.menuItems
com.example.app.MenuItem.MenuItem(String name, String description, Category category, double price, ArrayList< String > ingredients)
References com.example.app.MenuItem.setDescription, com.example.app.MenuItem.setPrice.
void com.example.app.MenuItem.setDescription(String description)
Referenced by com.example.app.MenuItem.MenuItem.
void com.example.app.MenuItem.setPrice(double price)
Referenced by com.example.app.MenuItem.MenuItem.
void com.example.app.MenuItem.editIngredients(ArrayList< String > ingredients)
String com.example.app.MenuItem.getName()
String com.example.app.MenuItem.getDescription()
Category com.example.app.MenuItem.getCategory()
double com.example.app.MenuItem.getPrice()
ArrayList< String > com.example.app.MenuItem.getIngredients()
void com.example.app.MenuItem.setCategory(String category)
References com.example.app.Category.CategoryNotAvailable, com.example.app.Category.getCategory.
static MenuItem[] com.example.app.MenuItem.getAllMenuItems()
static void com.example.app.MenuItem.removeMenuItem(MenuItem item)
Referenced by com.example.app.MenuItemPanel.initialize.
static ArrayList< MenuItem > com.example.app.MenuItem.getMenuItems()
Referenced by com.example.app.MenuItemPanel.refreshMenuList.
static MenuItem com.example.app.MenuItem.getMenuItem(String name)
Referenced by com.example.app.EditMenuItem.OnNameSelected, com.example.app.EditMenuItem.setBtnapply.
static Boolean com.example.app.MenuItem.MenuItemExists(String name, Category category)
Referenced by com.example.app.AddMenuItem.btnaddMenuItem.
void com.example.app.MenuItem.setName(String name)
void com.example.app.MenuItem.setCategory(Category category)
void com.example.app.MenuItem.setIngredients(ArrayList< String > ingredients)
void com.example.app.MenuItem.addMenuItem(MenuItem menuItem)